name: Trigger auto deployment for code-judge

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/code-judge-AutoDeployTrigger-28ff5de6-eaca-44c5-820e-fdbee73fa8a5.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CODEJUDGE_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: xwang971reg.azurecr.io
          registryUsername: ${{ secrets.CODEJUDGE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CODEJUDGE_REGISTRY_PASSWORD }}
          containerAppName: code-judge
          resourceGroup: workerapps-rg-xj
          imageToBuild: xwang971reg.azurecr.io/code-judge:${{ github.sha }}
          

     

