name: Trigger auto deployment for daprcertapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/daprcertapp-AutoDeployTrigger-218f3822-c459-459f-805b-a4345ab8bb61.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.DAPRCERTAPP_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: xwang971reg.azurecr.io
          registryUsername: ${{ secrets.DAPRCERTAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.DAPRCERTAPP_REGISTRY_PASSWORD }}
          containerAppName: daprcertapp
          resourceGroup: workerapps-rg-xj
          imageToBuild: xwang971reg.azurecr.io/daprcertapp:${{ github.sha }}
          

     

