name: Trigger auto deployment for ordersappnew3

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/ordersappnew3-AutoDeployTrigger-fba04d41-9cf1-472d-b08f-8cad1dcdf739.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ORDERSAPPNEW3_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: xwang971reg.azurecr.io
          registryUsername: ${{ secrets.ORDERSAPPNEW3_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ORDERSAPPNEW3_REGISTRY_PASSWORD }}
          containerAppName: ordersappnew3
          resourceGroup: workerapps-rg-xj
          imageToBuild: xwang971reg.azurecr.io/ordersappnew3:${{ github.sha }}
          

     

