name: Trigger auto deployment for testingone

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/testingone-AutoDeployTrigger-97a4e723-74d1-4308-a143-3f9531147aa4.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: xwang971reg.azurecr.io
          username: ${{ secrets.TESTINGONE_REGISTRY_USERNAME }}
          password: ${{ secrets.TESTINGONE_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: xwang971reg.azurecr.io/testingone:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.TESTINGONE_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n testingone -g workerapps-rg-xj --server xwang971reg.azurecr.io --username  ${{ secrets.TESTINGONE_REGISTRY_USERNAME }} --password ${{ secrets.TESTINGONE_REGISTRY_PASSWORD }}
            az containerapp update -n testingone -g workerapps-rg-xj --image xwang971reg.azurecr.io/testingone:${{ github.sha }}
